/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/AboutCard.vue')['default']
    AboutCardSection: typeof import('./src/components/AboutCardSection.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleCardSection: typeof import('./src/components/ArticleCardSection.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    FormButtonModal: typeof import('./src/components/Form/ButtonModal.vue')['default']
    FormInput: typeof import('./src/components/Form/Input.vue')['default']
    FormTextarea: typeof import('./src/components/Form/Textarea.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
  }
}
